//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesTo.FolderToCopy {
    
    
    public class Accountscollocation {
        
        public int Id {
            get {
            }
            set {
            }
        }
        
        public int Idaccount {
            get {
            }
            set {
            }
        }
        
        public int Idcollocated {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<decimal> Distancefrom {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<decimal> Distanceto {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<System.DateTime> Createdat {
            get {
            }
            set {
            }
        }
        
        public ClassesFrom.ClassesFromCopy.Account IdaccountNavigation {
            get {
            }
            set {
            }
        }
        
        public ClassesFrom.ClassesFromCopy.Account IdcollocatedNavigation {
            get {
            }
            set {
            }
        }
    }
}
