//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesTo.FolderToCopy {
    
    
    public class Account {
        
        public int Id {
            get {
            }
            set {
            }
        }
        
        public string Email {
            get {
            }
            set {
            }
        }
        
        public string Name {
            get {
            }
            set {
            }
        }
        
        public string Surname {
            get {
            }
            set {
            }
        }
        
        public string Password {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<int> Verificationcode {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<System.DateTime> Verificationcodevalid {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<int> Idrole {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<bool> Emailconfirmed {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<bool> Allowsnotifications {
            get {
            }
            set {
            }
        }
        
        public string Image {
            get {
            }
            set {
            }
        }
        
        public string Phonenumber {
            get {
            }
            set {
            }
        }
        
        public string Refreshtoken {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<System.DateTime> Refreshtokenvalid {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<System.DateTime> Createdat {
            get {
            }
            set {
            }
        }
    }
}
