//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesTo.FolderToCopy {
    
    
    public class Accountmetadatum {
        
        public int Id {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<int> Idaccount {
            get {
            }
            set {
            }
        }
        
        public int Gender {
            get {
            }
            set {
            }
        }
        
        public string Pesel {
            get {
            }
            set {
            }
        }
        
        public string Phone {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<int> Idgeographicregion {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<int> Idoccupation {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<bool> Issmoker {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<bool> Iswithanimals {
            get {
            }
            set {
            }
        }
        
        public string Metajson {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<System.DateTime> Createdat {
            get {
            }
            set {
            }
        }
    }
}
