//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesTo.FolderToCopy {
    
    
    public class Accountmode {
        
        public int Idaccount {
            get {
            }
            set {
            }
        }
        
        public int Mode {
            get {
            }
            set {
            }
        }
        
        public ClassesFrom.ClassesFromCopy.Account IdaccountNavigation {
            get {
            }
            set {
            }
        }
    }
}
