//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesTo.FolderToCopy {
    
    
    public class Accountscarslocation {
        
        public System.Nullable<int> Idaccount {
            get {
            }
            set {
            }
        }
        
        public string Name {
            get {
            }
            set {
            }
        }
        
        public string Surname {
            get {
            }
            set {
            }
        }
        
        public string Email {
            get {
            }
            set {
            }
        }
        
        public string Streetfrom {
            get {
            }
            set {
            }
        }
        
        public string Streetto {
            get {
            }
            set {
            }
        }
        
        public string Cityfrom {
            get {
            }
            set {
            }
        }
        
        public string Cityto {
            get {
            }
            set {
            }
        }
        
        public string Registrationplate {
            get {
            }
            set {
            }
        }
        
        public System.Nullable<int> Availableseats {
            get {
            }
            set {
            }
        }
        
        public string Brand {
            get {
            }
            set {
            }
        }
        
        public string Model {
            get {
            }
            set {
            }
        }
        
        public string Colour {
            get {
            }
            set {
            }
        }
        
        public string Rgb {
            get {
            }
            set {
            }
        }
    }
}
